= For Glory

== Introduction

This game was created to allow players to make zombie ninjas, axe
witches, necrodroids or whatever craziness they can think of. The
dungeon master can be riffing on the players actions and using random
tables to create emergent stories.

This game simulates a piece of fiction rather than reality. In this
story a bow and arrow may be a better weapon than a gun. The game using
a variety of random tables as seeds for fun at the table and players and
GM are expected to make up some table entries to suit the character and
world.

This game is easy to understand. Your characters attributes are measured
in the number of dice they roll. If your character has a _Power_ of 3,
they roll 3 dice.

The below rules describe the basic game in the fantasy genre.

== Mechanics
⚅ &#9861;
⚄ &#9860;
⚃ &#9859;
⚂ &#9858;
⚁ &#9857;
⚁ &#9857;
⛤ &#9956;
⛧ &#9959;
💀 &#128128;
⚔ &#9876;
🛡 &#128737;
🏹 &#127993;
🏺 &#127994;
🗡 &#128481;
🩸 &#129656;
☠ &#9760;

=== Overview

When a character wants to do something and the success or failure will
have a significant effect on the story, the player rolls a bunch of
six-sided dice. Each die that _beats_ the *Target number* of 3 is a
*hit*. Any attempted task may require one or more *hits* in order to
complete successfully.

Instant challenges, like jumping over a hole, require the *hits* be
completed in a single roll. Cumulative challenges, like breaking down a
door or defeating a _fire vole_, may be completed with cumulative
*hits*. Even if a challenge allows cumulative *hits*, it may be
beneficial to complete the challenge in a single action. Such as
smashing through a door with a single blow to surprise an enemy.

=== Chance of success table

This table shows the chance to achieve a certain amount of hits with
differing amounts of dice.

[cols=",,,,,,,,",options="header",]
|===
|d6 |0 hits |1+ |2+ |3+ |4+ |5+ |6+ |7+
|1 |50 |50 |8 |1 | | | |
|2 |25 |75 |33 |9 |2 | | |
|3 |12 |87 |56 |25 |8 |2 | |
|4 |6 |94 |73 |43 |20 |7 |2 |
|5 |3 |97 |84 |60 |34 |16 |6 |2
|6 |2 |98 |90 |73 |49 |28 |13 |5
|7 |1 |99 |95 |83 |63 |41 |22 |11
|===

=== Dice

Dice are the main unit of measure in the game. Character attributes are
measured in dice and you can gain or lose dice from your attributes.
Dice may be broken down into 6 pips. You may also gain or lose pips but
it has no mechanical effect unless you gain or lose 6 pips. The notation
`2d' indicates 2 six-sided dice. 2p indicates 2 pips.

A character may have a _Power_ of 3d and a sword which adds +2d for
their attack. This would make an attack roll of 5d. Each hit on that
roll will remove a 1 pip (1hp) of health from the target.

==== Terms

1d :: one six-sided die.
1Hd :: one _health_ die.
hit :: a roll of 4,5, or 6.
+1h :: add one hit to your roll.
1p :: one pip (pips are the dots on a 6-sided die)
1hp :: one _health_ pip.

==== Ways to roll your dice

1d :: Roll a six-sided die and use the face value.
2d :: Roll two dice and add the face values together.
d2 :: Roll a six-sided die and 1-3 = 1, 4-6 =2.
d3 :: Roll a six-sided die and 1-2 = 1, 3-4 = 2, 5-6 = 3.
d12 :: Roll a d2. On a 1, roll a d6. On a 2, roll a d6+6.
d66 :: Take two dice and choose one to be 10x value. Roll them both so a roll of 3 & 4 would be 34.

=== Stunts

Stunts are the way you describe the actions your character takes. There
are three levels of stunts and each one adds another die to your roll.
Level 1 stunts simply describe your action in a cool way. Level two
stunts incorporate the story, the environment, or one of the character’s
doom. Level 3 stunts are determined by the judge at the time.

[arabic, start=0]
* I attack with my sword *0 dice*.
* I slash at the monster’s neck *+1 die*.
* I fling some of the swamp muck into the creatures eyes before driving my sword in. *+2 dice*.
* Something so cool that it belies an example. *+3 dice*.

Co-operative stunts are when you include another PC in your stunt. The
included PC may loan the player dice of the appropriate attribute for
this action. They cannot use those dice on their next turn.

== Character Creation

* Choose one of your attributes to get an extra die and give the
remainder of the attributes one die.
* Choose or roll an occupation.
* Choose or roll a piece of equipment.

=== Attributes

Attributes are measured with dice. The number of dice you have in an
attribute is how many dice you roll in a challenge that uses that
attribute. The default amount, for a healthy character, in all 5
attributes is 1 die. Each die has 6 pips. Sometimes the pips are used as
a unit of measure.

Attribute dice and pips maybe gained and lost during play. Some
attribute effects may take longer to heal or even be permanent if
required within the narrative.

Losing or gaining pips has no mechanical effect until you lose or gain 6
pips. At which point you would roll one less die for contests which use
that attribute.

Being reduced to zero pips in any attribute will have the effects
described below. In addition, for any contest that use an attribute that
has been reduced to zero, you would use 2 dice and take the lower
result.

==== Power Dice

Attacking, lifting, pushing, breaking, and sometimes climbing.

==== Agility Dice

Defending, running, jumping, sneaking, hiding, dodging, swinging, and
sometimes climbing

==== Brain Dice

Intelligence, wisdom, personality, disguises, discernment, perspicacity,
spells, clues, psychic abilities, languages, codes, history.

==== Health Dice

Health Points, stamina, fatigue, carrying, breath holding, disease
resistance, poison resistance.

While the default _health_ amount is 1 die, additional dice are awarded
based on physical size. Humanoid sized characters, whether very small or
very large, gain 1 additional _health_ die. If you want to play a
character so small or large that it should be reflected in the
mechanics, you would instead gain 0 or 2 _health_ dice. Smaller targets
are harder to hit and larger targets are easier, as discussed in the
_combat_ section.

Damage from combat temporarily removes pips from your _health_ dice.
Taking 6 points of damage reduces your _health_ dice by 1 and requires a
roll on a wound table. Being reduced to 0 _health_ dice means you are
_exhausted_. _Ehausted_ characters move at half speed and use half their
dice for any physical activity.

==== Dare Dice

Daring, focus, luck, chutzpah, fate, karma.

If you have time to focus before executing a task you may add your
_dare_ dice to your roll. Dare may also be added if do not have time to
focus but, those dice are added to the Dungeon Master’s Doom Pool.
Temporary _dare_ die are lost at the end of a session and whenever a
_fumble_ is rolled.

===== Dare checks

The *DM* may call for a _dare check_ any time it is warranted by the
story. Often, only a single success is required to pass a dare check and
avoid some misfortune.

=== Occupations

[arabic]
. *Hunter, Ranger* +
+1d _Power_, +1d _agility_, a bow (+2d) & 12 arrows, _healing herbs_
(6), dagger (+1d fast), combat skills Death Throe:
[arabic]
.. {blank}
.. {blank}
.. {blank}
.. {blank}
.. Final strike. Full strength attack and 2d _Critical Hit_.
.. Final strike. Full strength attack and 1d+7 _Critical Hit_.
. *Guard, Soldier, Tax Collector* +
+2d _agility_, chain mail armor +2, choose one extra from _equipment_,
10cp, sword (+2d), combat skills
. *Executioner, Mercenary, Barbarian* +
+1d _Power_, +1d _agility_, leather armor +1, black hood or furry,
horned helm, sack, 10cp, battle axe (+2d+1h slow), combat skills
. *Alchemist, Wizard* +
+2d _brains_, _6 flash powder_, 1 alchemist spell, dagger (+1d fast),
arcana skills
. *Witch, Warlock, Midwife* +
+1d _brains_, +1d _agility_, _6 healing herbs_, 2 witch spell, staff
(+1d), arcana(S), forage(S)
. *Thief, Rogue, Assassin* +
+1d _Agility_, +1d _brains_, +1d _dare_, 4 Daggers (+1d, fast),
lockpick, _poison_ (6), Thief’s skills

=== Combat skills

+2h Combat related rolls. +1 Crit rolls. This character can divide up
their attack dice between opponents.

=== Arcana skills

+2h for magic related tasks.

=== Thief’s skills

+2h for all rolls a thief may excel at. Concealable weapons confer +3d
and ignore armor on surprise attacks.

==== Poison

There are many kinds of poison but the rules for generic poison are as
follows. Poisoned weapons cause the number of hits that do damage to a
target to double. Poisoned weapons remain poisonous for a single combat
encounter in which the weapon is used.

Applying poison to a weapon has a difficulty of 3. A thief would roll
_agility_ + 2h and likely add their _dare_ as well. A failed check
wastes the poison and causes 1d damage.

Drinking or eating poison requires 4 _health_ hits. Failing inflicts
4d6hp.

=== Equipment (3d6, +/- to duplicates)

[arabic, start=3]
. Chalk
. Compass
. Donkey (roll on _name_ table)
. Flash powder (6) Allows you to withdraw from melee freely, exit the
room, stun a target.
. Sack
. Healing herbs (6) +2h to a _healing_ check.
. Lantern and flint & steel
. Rope, 50’
. Rations (6)
. Torches (6) and flint & steel
. Crowbar
. Backpack
. Shield
. Grappling hook
. Poison (6) See the poison rules under _thief skills_.
. Spyglass
. Bucket

=== Dooms (d66)

Every great hero has flaws. Every time you use your doom to effect the
story, you earn a temporary _dare_ die. Roll d66 on this table

[arabic]
. {blank}
[arabic]
.. Addictive personality
.. Always has to be right
.. Bad tempered
.. Complains
.. Compulsive
.. Cursed
. {blank}
[arabic]
.. Death wish
.. Drunkered
.. Fear of heights
.. Fear of small spaces
.. Fear of snakes
.. Fear of spiders
. {blank}
[arabic]
.. Fidgets
.. Financially irresponsible and in debt
.. Fool for love
.. Foolhardy
.. Gambles
.. Glass half empty
. {blank}
[arabic]
.. Ill mannered
.. Klepto
.. Lazy
.. Low self-esteem
.. Narcissistic
.. Obsessed with beauty
. {blank}
[arabic]
.. Obsessed with treasure
.. Paranoid
.. Perfectionist
.. Rose colored glasses
.. Says the wrong thing
.. Slovenly
. {blank}
[arabic]
.. Tardy
.. Unlucky
.. Vain
.. hh
.. hh
.. hh

== Weapons

Weapons add dice and, possibly, automatic hits to combat rolls.

Weapons have special tables for critical hits. Players should receive a
handout which includes the table for any items that require it.

=== Generic Weapon Types

*Unarmed* :: 0d. Example: Fist
*Small* :: 1d. Cost: 1cp. Note: May be concealable or throwable. Example: Dagger, club
*Small ranged* :: 1d. Cost: 4cp. Note: 12 ammo/slot, 1cp each. Example: Crossbow, handgun
*One-handed* :: 2d. Cost: 10cp. Example: Sword, Mace, Submachine gun, Beam Staff
*Large ranged* :: 2d. Cost: 50cp. Note: 6 ammo/slot. Cost: 10cp. Example: Bow, Rifle
*Two-handed* :: 3d. Cost: 60cp. Note: Rare, Takes 2 gear slots, *Agility* -1d. Example: Great sword, battle axe

=== Generic Critical Hit Table

[arabic]
. Solid hit, +1 damage
. Prone
. Entangled
. Disarmed
. Gross hit, +2 damage
. Bleeding
. Armor/shield Damaged
. Entangled
. Arm maimed
. Disgusting hit, +3 damage
. Blinded
. Brained / Stunned
. Eviscerated / Impaled

=== Fist

0 additional dice are added to the _power_ roll.

[arabic]
. Black eye. +1 damage and possible quick hand action.
. Uppercut knocks them flat.
. Kidney shot. Fall over and actions are at -1d.
. Disarmed. Weapon thrown 5d’ away.
. Uppercut. +2 damage.
. Haymaker. +2 damage and knock them flat.
. Eye strike. -1 attack until healed.
. Knee damaged. Movement reduced by half. -2 *power* and *agility*
reduced to 1.
. Disarmed and weapon grabbed. Make a free attack with it now.
. K.O. prone and make 3 *health* hits to awaken.
. Neck strike. +3 damage, drop weapon, and lose a turn.
. Chained combo. Keep rolling attacks until one fails or you fumble.
. Pull their still beating heart from their chest and show it to them.

=== Dagger *melee*

+1d. Concealable, throwable.

[arabic]
. Vicious blow. +2 damage
. Bloody mess. Double damage
. Internal injuries. 5s explode as well.
. You end up behind your opponent and they did not see where you went.
. Artery. +2 damage and 2 damage/round until staunched.
. Skillful blow. Attack this opponent again or attack another target
melee or ranged.
. The slow blade finds its target. Ignore armor and +2 damage.
. Forceful strike. +2d and the target must make an _agility_ 3 check or
fall/pushed back. Depending on size.
. Grapple them and stab again for d6+2 damage. They must break free on
their turn or double damage and ignore armor next round.
. Massive strike for +2d6 damage and your opponent is thrown prone.
. Too fast to see. 1d6 damage to all close opponents.
. Eviscerated - Death save and scoop your guts up.
. Dagger thrust under the chin pops out the top of the head.

=== Dagger *ranged*

[arabic]
. Precision strike +1d6 damage.
. Stuck in bone. -1d action until pulled out for 1d6 blood loss.
. {blank}
. {blank}
. Pin limb to the wall.
. Dagger in the eye. +2d6 damage.
. Pierces kidney. 1d6 damage + 1d6 damage after taking any action.
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. Shot in the eye blasts out of the back of the skull, pinning the brain
to the wall.

=== Sword

+2d

[arabic]
. Gain +1 *Armor* agianst this opponent until next round.
. Opponent cannot crit on you with their next attack.
. Opponent loses their highest rolled attack die if they attack you.
. +2 Damage to weapon arm. -2d attack.
. Bleeding wound. +2 damage and 1 damage/round until bleeding is
stopped.
. Powerful strike. +3 damage and 3h _agility_ check or be pushed back.
. Skillful attack. Choice of grappled, pushed back on other effect.
. Trip up. +4 damage and 4h _agility_ check or prone.
. Weapon arm removed and smacks another opponent.
. Gory attack. +2d6 damage and other opponents may flee.
. _You killed my father. Prepare to die_ +d66 damage.
. Speed demon. Make 1d6 more attacks against opponents in close range.
. Blur of blades. All opponents in melee range take 2d6 damage.

=== Bow & Arrow

+2d (no bonus if untrained)

[arabic]
. Shoot the weapon out of their hand or damage their weapon.
. Shoot again at the same or a different target.
. Take 2 more shots on any targets.
. Arrows stick in opponent reducing 1 die from all actions until healed.
. Take 3 more shots on any targets.
. Head shot, 6 damage.
. Impale limb.
. Arrow sticks in opponent reducing 2 die from all actions until healed and reducing movement to 0.
. Keep making attacks but only at new opponents.
. Arrow pierces for 1d6 damage and another opponent for 1d6 as well.
. Neck sprays blood (1d6 damage). Lose 1d6hp per round and blinds other opponents (-2d until eyes are wiped clean).
. Ignore armor and +2d6 damage.
. Head shot (6 damage) in the zone. Roll an attack but each _hit_ is a head shot (6 damage) on another opponent.

=== Battle Axe

+2d+1h, slow

[arabic]
. +2 hit
. Opponent’s armor reduced by 1
. Opponent’s weapon and shield is destroyed
. Dominant limb is severed.
. Opponents armor/shield is destroyed, +1d6 hits.
. Leg is severed.
. Both arms are severed.
. Make another attack at any single,_near_ opponent at +5d.
. Make another attack at +5d against any number of _near_ opponents.
. Eviscerated (2hd & 6hp/round). Other opponents may slip and fall.
. Beheaded (4hd). Make another attack at any single,_near_ opponent at
+5d.
. Chopped down the middle (6hd) with halves blasting out left and right
and knocking nearby opponents prone. All opponents run in fear or beg to
serve you.
. Cleaved at the trunk (8hd). Make 3 more attacks at any _near_
opponents at +5d and ignoring armor.

=== Ammunition

Ammo is unlimited and ignored.

==== Optional ammo rules

Ammunition is an item like any other. Each gear slot of ammo contains a
multiple of 6 shots. You can use d6s to track ammo.

== Armor

Armor reduces *agility* Dice and incoming damage. If *agility* is at
one, *power* is reduced instead.

Light armor :: -1 damage, -1 *agility*
Heavy armor :: -2 damage, -2 *agility*
Shield :: -1 damage, -1 *agility*. Shield may also help mitigate injuries
and can be easily dropped or thrown in order to use the lost _agility_
die.

== Combat

Combat takes place in rounds with each player and non-player character
(NPC) usually taking a single turn in the round. Each round takes 10
seconds which can be tracked with dice by adding another die for each
minute of combat. If you are tracking time closely, each combat
encounter is rounded to the nearest 10 minute increment to account for
catching your breath and patching yourself up after combat.

=== Initiative

To determine who goes when, each player rolls an _agility check_ the
fastest monster’s speed. Winners take their turns before the monsters
and losers go after. There maybe other factors which affect the turn
order such as minions typically going last.

=== Attacking

Attacking a target is a challenge roll like any other. Roll as many dice
as you can. This is usually *Power* dice + Weapon dice.

Some skills, such as _combat_ add extra _hits_ to your roll.

Each die that comes up above the target number (usually 3) is counted as
a *hit* and subtracted from the target’s *health pips*. Armor allows a
target to avoid a certain number of *hits* but *hits* that were the
result of a roll of *6* are not effected by armor.

The number of dice rolled may be altered as described in the _Mechanics
Overview_ section. Additionally, the _dungeon master_ may determine that
aspects of the environment alter the number of dice rolled.

The relative size of the combatants effects the dice roll as well.
Smaller targets are harder to hit and larger targets easier. Attacking a
target one size larger adds two dice to the roll and is multiplied by
two for each additional size difference. So a gnome attacks a giant with
4 extra dice.

NPCs and monsters do not make attack rolls. Rather, players roll for
defense when monsters attack.

=== Defending

Players roll their _agility_ to defend. The player’s _hits_ are
subtracted from the monster’s attack. The remainder are subtracted from
the players _health pips_.

PCs and NPCs that are reduced to 0 _health pips_ are _defeated_.

Armor has the effect of making some of a Player’s agility into automatic
successes. These dice cannot be used for agility related actions while
armor is worn. A player wearing leather armor with 3 _agility_ dice
would only roll 2 dice as and add a single success to the result. If
they try to jump over a pit wearing their armor, they only roll two
dice.

=== Disengaging

Moving away from an opponent that is in active melee combat with you
incurs a free attack.

=== Alternate Combat Actions

* Distract - If you are not the main target, attack and remove _hits_ -
target’s _intelligence_ from their next attack roll in this round.
* Disarm - Roll your _agility_ against the target’s _power_ to cause
them to drop their weapon.
* Trip - Roll your _power_ against the target’s _power_ + _size_.
* Parry - Use _power_ instead of _agility_ to defend against the next
attack this targets makes.
* Push - Use _power_ - target’s _size_ to beat target’s _agility_ and
knock back 5’ + _hits_
* Grapple - use agility to get passed defense and ignore armor. Affected
by reach of the defender’s weapon. After success use power to defeat.
* Disengage - Use _agility_ to beat target’s _agility_ to move away
without incurring an attack. Failure means you can still move away but
you incur an attack no matter what.

=== Critical Hits

If double 6s are rolled, you will also roll on the critical hit table
for that weapon. If three 6s are rolled, roll 1d6+6 on the critical hit
table. Additional 6s add a +1 each to the roll. Some npcs may have their
own crit tables but, in general, NPCs do not crit. The effect of rolling
double 6s on challenges other than combat are at the judges discretion.

=== Fumbles

If more than 50% of the dice rolled come up 1, it is a fumble.

*One Shot:*

==== Player Character Fumble Table

Character fumbles on attacks are specific to the character. They
following table may be used as a guide.

[arabic]
. Fall on your sword. Roll _power_ against yourself.
. {blank}
. {blank}
. {blank}
. {blank}
. Trip into your opponent. If the attack has any hits, +2 hits. You are
prone.

== Damage

=== Healing

There are three types of damage that may be applied to attributes. 1.
Normal damage that represents various types of wounds and heals at one
pip per day. Two pips for days only spent resting. Field medicine,
magical healing and potions all heal this type of damage and, usually,
only _health_ pips. 1. Momentary damage that heals after a few moments
of rest. Such as when losing _health_ pips to overexertion. 1. Permanent
damage that does not heal normally and may require completing some great
quest to recover.

=== Death

Most combat damage suffered is subtracted from _Health Pips_. Losing
your last _health_ pip does not mean you are dead. Each time the last
pip of a die is lost, the character must roll a their _health dice_ on
the _Table of Terrible Injuries_. If they have no _health dice_ left to
roll, they must roll on the mortal injury table. For example; a
character with 2 _health dice_ will roll on a table when they lose their
7th _health pip_ and their last _health pip_. Characters with no _health
dice_ must roll on the _Mortal Injuries_ table every time they take any
damage. True death can only come as the result of a roll on the _Mortal
Injuries_ table and will trigger the character’s _Death Throe_.
Additiotally, characters with no _health dice_ are exausted and use only
half their dice on any roll.

=== Tables of Terrible Injuries (health dice)

[arabic]
. Roll on the _Table of Mortal Injuries_
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. It only pisses you off. Regain 1d6hp and take a turn.

=== Table of Mortal Injuries (3d)

[arabic]
. Instant death. Describe your gruesome demise.
. Major artery. Die next round unless first aid is received.
. Bleeding out. Die in 1d rounds unless first aid is received.
. Dismembered.
. Internal injuries.
. Blinded.
. Bleeding wound.
. K.O.
. Defeated. You are down and can only crawl away.
. Brained. Lose half your _brains_.
. Downed. You are on the ground next round and can get up the following
round.
. Walk it off. You lose a turn.
. Disarmed. You lose your weapon.
. You are fine. No effect.
. It makes you stronger. Gain 1d _health pips_.
. Second wind. Earn back 1d _health dice_. It is your turn.

=== Healing

*Health* and other attribute Point damage heals between episodes and
many scenes. Narrative damage from some crits, environmental effects, or
strong monsters lasts longer. It may be permanent or require a long
rest, or a quest to heal.

== Movement and Range

Distance is divided into 4 bands. _Close_, _Near_, _Far_, and _Very
Far_. The actual size of the ranges expands as they move out. It is
always possible to move from _Near_ to _Close_ on your turn but other
distances are up to your DM.

== Size

Size is also measured in dice.

* 1pip - Tiny (bird)
* 1d - Small (gnome): +1d _agility_, -1d _power_; Inventory:
6+__health__; Can use of _agility_ dice to attack but then cannot use it
for defense this turn.
* 2d - Normal (human): +1d _health_; inventory: 10+__health__. The word
**
* 3d - Big (Andre): +2d _health_, -1d _agility_; inventory:
14+__health__
* 5d - Giant (tree)
* 12d - Massive (building)

== Magic Items

Magic is not a form of energy that objects may be imbued with. There is
no +1 magic sword. Magic is desire given form. The most important aspect
of any magical item is why is it magic.

=== Dahgtar’s Doom

+3d Magic Sword

Created in eons ago in the subterranean city of _Machtuul_, many heros
sacrificed their lives to inter their spirits in this blade’s ancient
steel. The blade smells of tears and weilding the blade gives the holder
a feeling of great personal sadness (*doom*). Only 38 more of this
blade’s ancient enemy need be killed in order to free the spirits inside
and turn the blade into a rusted, old +1d sword.

[arabic]
. Gain +1 *Armor* agianst this opponent until next round.
. Opponent cannot crit on you with their next attack.
. Opponent loses their highest rolled attack die if they attack you.
. +2 Damage to weapon arm. -2d attack.
. Bleeding wound. +2 damage and 1 damage/round until bleeding is
stopped.
. Powerful strike. +3 damage and 3h _agility_ check or be pushed back.
. Skillful attack. Choice of grappled, pushed back on other effect.
. The sword bursts into flame. Flammable targets alight and take d1 fire
damage/round. The sword remains in flames until the danger has passed
(even if the character thinks the danger has passed).
. Weapon arm removed and smacks another opponent.
. Gory attack. +2d6 damage and other opponents may flee.
. _You killed my father. Prepare to die_ +d66 damage.
. Speed demon. Make 1d6 more attacks against opponents in close range.
. Blur of blades. All opponents in melee range take 2d6 damage.

== Spells

Casting spells is simply a matter of rolling _Brains_. Spells can be
cast until they are lost. Lost spells return the following morning. Lost
spells may be cast at the cost of 1 health pip per casting.

=== Alchemist spells

The alchemist may sacrifice their own body to add to the power of the
casting. Remove _Power_, _Agility_, or _Health_ which heal normally.

==== Magic Missile

*Spell Name* (1d, roll once)

[arabic]
. *Acid rain* melts them
. *Electricity* lets you see skeleton
. *Exploding Fireballs*
. *Rainbow Eye Beam*
. Fire blast from hands
. Ground eruptions

===== Effects (based on number of hits)

[arabic, start=0]
. Missile effects you. You take 2d6 damage. Spell lost and two side
effects.
. Missile effects you. You take 1d6 damage. Spell lost and one side
effect.
. Missile effects you. 1d6 damage. Spell lost.
. No effect. Spell lost.
. No effect.
. 5 damage to a single target.
. 2d6 damage to a single target who is prone.
. 4d6 damage that may be divided among multiple targets who are prone.
. 4d6 damage that may be divided among multiple targets who are also
prone and 1d6 damage to everyone not targeted, including allies.
. Everyone takes 2d6 damage and is prone.

===== Side Effects

Each side effect happen only once. Once every effect is taken, PC
becomes an NPC lizard person and attacks everything.

*Double ones:* +
1. Hair turns a bright color. 1. Skin turns a bright color. 1. Fingers
become tentacles.

*Triple ones:* +
1. Skin becomes scaley, +1 Armor 1. Extra eye grows in forehead. +1d for
perception and anti-surprise. See _Magic Mouth_ if you if you already
have a mouth there.

*Quadruple ones:* +
1. Lizard brain. +1d _Agility_ and can only eat live insects.

==== Magic Mouth

===== Effects (based on number of hits)

[arabic, start=0]
. You begin yelling uncontrollably. Spell lost and two side effects.
. You begin yelling uncontrollably. Spell lost and one side effect.
. You begin yelling uncontrollably. Spell lost.
. No effect. Spell lost.
. A mouth appears on a chosen surface and speaks a phrase of your
choosing when a particular trigger of your choosing occurs.
. A large mouth appears under an opponent, biting for 1d6 damage. Caster
may choose entry 2 instead of this one.
. Your opponent’s weapons gain mouths and attack their owners. Caster
may choose entry 2 or 3 instead of this one.
. Your mouth becomes a giant, fanged maw for the remainder of this
battle. You may immediately attack with _Strength_ +3d. Caster may
choose entry 2 instead of this one.
. You face and hands become mouths. You can make 3 +3d attacks/round for
the remainder of the encounter.
. Every creature in the local area gains multiple mouths and begins
saying inappropriate things. Many creatures are horrified and run off.
Wears off in one day.

===== Side Effects

Each side effect happens only once. Once every effect is taken the
spellcaster becomes a giant mouth with legs and attacks everything.

===== Double ones:

[arabic]
. Gain a mouth on your forehead. If you already have an eye there, other
people may ask the new face questions as it has special knowledge.
. {blank}
. Your eyes are small mouths. You no longer see color but you can see
30’ in the dark using echo location.

===== Triple ones:

[arabic]
. Large fangs. +1d bite attack.
. Hands become mouths. You cannot hold weapons properly but you have two
+1d bite attacks/round.

===== Quadruple ones:

[arabic]
. Mouth on your backside that you now use for speaking.

=== Midwife spells

Midwives may choose to cast at the level cast or any lower level. Triple
ones means the spell is lost after this casting.

==== Wood Weird

[arabic, start=0]
. No effect. Spell lost. Tangling plants grow from the floor and walls.
. No effect. Spell lost. Vines and branches grow from all nearby wood
objects.
. No effect. Spell lost and a small log falls on a random person. 1hp if
no helm.
. No effect. Spell lost.
. Roots protrude from the ground trapping opponents who must make a
strength check to escape.
. A wooden spike shoots up from the ground for 1d6 damage.
. Wooden objects may be warped to ruin weapons or seal doors.
. 6d wooden bolt attack divided by up to 6 targets.
. Wood may be formed into a shape.
. Summon Larch (P4d A2d B0d H3d, move slow, 2 Attacks/round)

==== Magic Shield

[arabic, start=0]
. No effect. Spell lost and you are locked in a 6d force prison for 10
rounds.
. No effect. Spell lost and
. No effect. Spell lost and
. No effect. Spell lost.
. Personal shield provides +3 armor for this round.
. Force ball attack 4d, ignore armor.
. Create a wall the size of 3 tower shields that can provide +1 armor
and protect 3 people or bar a door with H3d.
. Create an invisible force field in the form of a craft which you can
travel around in for up to 1 hour.
. Create an invisible force field that can be manipulated with your
mind. It can protect 4 people with +2 armor. If you concentrate, it can
protect them as they move.
. Create an invisible force field in the form of a craft which the party
can travel around in for up to 1 hour.
. Invisible force armor gives you +3d _Power_, +3 Armor, double jump,
and move.
. Create a force field the size of house with 12Hd that can push a
house.

== Characters
=== Slonack *Ranger*
==== Attributes
*Power* &#9861;&#9861;&#9861;

*Agility* &#9861;&#9861;

*Brains* &#9861;

*Health* &#9861;

*Dare* &#9861;

==== Skills

Combat &#9861;&#9861;&#9861;

Ranged attacks &#9861;

==== Equipment

Healing herbs, rope, string, shovel, water skin

&#9634;

&#9723;

&#39633;


==== Weapons

===== &#127993; Bow &#9861;&#9861;

[arabic]
. Shoot the weapon out of their hand or damage their weapon.
. Shoot again at the same or a different target.
. Take 2 more shots on any targets.
. Arrows stick in opponent reducing 1 die from all actions until healed.
. Take 3 more shots on any targets.
. Head shot, 6 damage.
. Impale limb.
. Arrow sticks in opponent reducing 2 die from all actions until healed and reducing movement to 0.
. Keep making attacks but only at new opponents.
. Arrow pierces for 1d6 damage and another opponent for 1d6 as well.
. Neck sprays blood (1d6 damage). Lose 1d6hp per round and blinds other opponents (-2d until eyes are wiped clean).
. Ignore armor and +2d6 damage.
. Head shot (6 damage) in the zone. Roll an attack but each _hit_ is a head shot (6 damage) on another opponent.

===== &#128481; Dagger &#9861;

Concealable, throwable.

====== Melee

[arabic]
. Vicious blow. +2 damage
. Bloody mess. Double damage
. Internal injuries. 5s explode as well.
. You end up behind your opponent and they did not see where you went.
. Artery. +2 damage and 2 damage/round until staunched.
. Skillful blow. Attack this opponent again or attack another target
melee or ranged.
. The slow blade finds its target. Ignore armor and +2 damage.
. Forceful strike. +2d and the target must make an _agility_ 3 check or
fall/pushed back. Depending on size.
. Grapple them and stab again for d6+2 damage. They must break free on
their turn or double damage and ignore armor next round.
. Massive strike for +2d6 damage and your opponent is thrown prone.
. Too fast to see. 1d6 damage to all close opponents.
. Eviscerated - Death save and scoop your guts up.
. Dagger thrust under the chin pops out the top of the head.

====== Thrown

[arabic]
. Precision strike +1d6 damage.
. Stuck in bone. -1d action until pulled out for 1d6 blood loss.
. {blank}
. {blank}
. Pin limb to the wall.
. Dagger in the eye. +2d6 damage.
. Pierces kidney. 1d6 damage + 1d6 damage after taking any action.
. {blank}
. {blank}
. {blank}
. {blank}
. {blank}
. Shot in the eye blasts out of the back of the skull, pinning the brain
to the wall.

==== Death Throe
[arabic]
.. {blank}
.. {blank}
.. {blank}
.. {blank}
.. Final strike. Full strength attack and 2d _Critical Hit_.
.. Final strike. Full strength attack and 1d+7 _Critical Hit_.

== THE END

⛤ &#9956;
⛧ &#9959;
💀 &#128128;
⚔ &#9876;
🛡 &#128737;
🏹 &#127993;
🏺 &#127994;
🗡 &#128481;
🩸 &#129656;
☠ &#9760;
